// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticalItem: typeof import('./src/components/artical/ArticalItem.vue')['default']
    ArticalLabel: typeof import('./src/components/label/ArticalLabel.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor/MarkdownEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
